version: "3.7"

services:
  postgres:
    image: postgres
  back-end:
      image:  node
      depends_on:
        - postgres
      ports:
        - 1337
  fron-end:
      image: node
      depends_on:
        - back-end
      ports:
        - 8080
        - 443
  pgadmin: # UI for database
    image: dpage/pgadmin4
    depends_on:
        - postgres
    ports:
      - 5432

  