version: "3.9"

services:

############################################### database ######################################
  postgres:
    container_name: postgresql 
    image: postgres
    environment:
      - POSTGRES_DB=chat_pong
      - POSTGRES_USER=transcendence
      - POSTGRES_PASSWORD=transcendence
    ports:
      - 5432:5432
  ############################################### start backend ################################
  back-end:
      container_name: back-end 
      build:
        context: ./docker/.
        dockerfile: back-end.dockerfile
      depends_on:
        - postgres
      ports:
        - 1337:1337
        - 3000:3000
  ############################################### start front-end ###############################
  fron-end:
      container_name: front-end 
      build:
        context: ./docker/.
        dockerfile: front-end.dockerfile
      depends_on:
        - back-end
      ports:
        - 8080:8080
        - 443:443
  ############################################### start UI ###############################
  pgadmin: # UI for database
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
        - postgres
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8888:80

  
